# Generated by Django 3.2.7 on 2021-09-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('gitLink', models.CharField(blank=True, max_length=255)),
                ('liveLink', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
