# Generated by Django 3.2.7 on 2021-09-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mainImage',
            field=models.ImageField(default='default.jpg', upload_to='project_images'),
        ),
    ]
