# Generated by Django 3.2.7 on 2021-09-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_long',
            field=models.TextField(blank=True),
        ),
    ]
