# Generated by Django 3.2.7 on 2021-09-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_description_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
